spring:
  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是100%,全部都需要。默认是 0.1

  zipkin:
    base-url: ${zipkin.base-url} # 指定了 Zipkin 服务器的地址
  cloud:
      bus:
        trace:
          enabled: true
        enabled: true
  rabbitmq:
      host: ${rabbitmq.host}
      port: ${rabbitmq.port}
      username: ${rabbitmq.username}
      password: ${rabbitmq.password}
      virtual-host: ${rabbitmq.virtual-host}

server:
  port: 14000
zuul:
   routes: # 自定义各模块的路由,默认模块名
    producer-db : /p/**
    consumer-db : /c/**
    system : /s/**
    websocket : /ws/**
#  SendResponseFilter:
#    post:
#     disable: true #禁用SendResponseFilter 过滤器

      
