spring:
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    virtual-host: ${rabbitmq.virtual-host}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
turbine:
  stream:
    port: 8989  #默认8989