spring:
  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是100%,全部都需要。默认是 0.1

  zipkin:
    base-url: ${zipkin.base-url} # 指定了 Zipkin 服务器的地址
# profiles:
#    active: sharding
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
    virtual-host: ${rabbitmq.virtual-host}

server:
  port: 13001

#     defaultZone: http://localhost:7000/eureka/
#feign:
#    hystrix:
#      enabled: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
logging:
 level:
  org:
   springframework:
    web:
     servlet:
      DispatcherServlet: DEBUG

