spring:
  sleuth:
     sampler:
       probability: 1.0 # 将采样比例设置为 1.0，也就是100%,全部都需要。默认是 0.1
  zipkin:
      base-url: ${zipkin.base-url} # 指定了 Zipkin 服务器的地址
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    virtual-host: ${rabbitmq.virtual-host}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}

server:
  port: 13002

feign:
    hystrix:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream #暴露到HystrixDashBoard监控的节点
logging:
 level:
  com:
   demo: DEBUG
  org:
   springframework:
    web:
     servlet:
      DispatcherServlet: DEBUG