spring:
  sleuth:
     sampler:
       probability: 1.0 # 将采样比例设置为 1.0，也就是100%,全部都需要。默认是 0.1
  zipkin:
      base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: demo
    username: lancer
    password: 123456

server:
  port: 13002

feign:
    hystrix:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream #暴露到HystrixDashBoard监控的节点
logging:
 level:
  com:
   demo: DEBUG
  org:
   springframework:
    web:
     servlet:
      DispatcherServlet: DEBUG